artifact_uri: file:///C:/Users/Rusinov.DS/PycharmProjects/ML_project/dns_purchase/artefacts/980200151464093923/7ebc9cb53f5c487b987c1fc2df4aca97/artifacts
end_time: 1734336760032
entry_point_name: ''
experiment_id: '980200151464093923'
lifecycle_stage: active
run_id: 7ebc9cb53f5c487b987c1fc2df4aca97
run_name: FCNetwork_1
run_uuid: 7ebc9cb53f5c487b987c1fc2df4aca97
source_name: ''
source_type: 4
source_version: ''
start_time: 1734336759206
status: 4
tags: []
user_id: Denis Rusinov
