artifact_location: file:///C:/Users/Rusinov.DS/PycharmProjects/ML_project/dns_purchase/artefacts/964258905629541857
creation_time: 1734332735675
experiment_id: '964258905629541857'
last_update_time: 1734332735675
lifecycle_stage: active
name: prophet_test
