artifact_location: file:///C:/Users/Rusinov.DS/PycharmProjects/ML_project/dns_purchase/artefacts/738681368043081300
creation_time: 1734058631090
experiment_id: '738681368043081300'
last_update_time: 1734334629083
lifecycle_stage: deleted
name: LSTM_purchase_model
tags: {}
