artifact_location: file:///C:/Users/Rusinov.DS/PycharmProjects/ML_project/dns_purchase/artefacts/980200151464093923
creation_time: 1734329177469
experiment_id: '980200151464093923'
last_update_time: 1734329177469
lifecycle_stage: active
name: PyTorch_test
